repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace


  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
        args:
          - --line-length=85
          - --target-version=py311
          - --skip-string-normalization

  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.0
    hooks:
      - id: isort
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    - id: mypy
      args:
        - --explicit-package-bases

  - repo: local
    hooks:
    - id: ruff
      name: ruff
      entry: ruff
      language: system
      types: [ python ]
